### ISSUE TITLE
connect error: Transport endpoint is not connected (107)

### ISSUE THREAD

**Issue by loglux** [pFenners/mijia-sensor-domoticz#6]
I have set up MAX and ID but can't get the data
What I do wrong?

domoticz@housespririt:~/domoticz/plugins/mijia-sensor-domoticz$ sudo python3 domoticz_mijia.py

1: updating
connect error: Transport endpoint is not connected (107)

**Comment by loglux** [comment]
domoticz@housespririt:~/domoticz/plugins/mijia-sensor-domoticz$ sudo python3 domoticz_mijia.py

1: updating
Mi Sensor: 4C:65:A8:DD:D4:EA
Firmware: 00.00.66
connect error: Transport endpoint is not connected (107)
connect error: Transport endpoint is not connected (107)
Traceback (most recent call last):
  File "domoticz_mijia.py", line 92, in <module>
    update("4C:65:A8:DD:D4:EA","241")
  File "domoticz_mijia.py", line 61, in update
    print("Name: {}".format(poller.name()))
  File "/home/domoticz/domoticz/plugins/mijia-sensor-domoticz/mijia/mijia_poller.py", line 180, in name
    return ''.join(chr(n) for n in name)
TypeError: 'NoneType' object is not iterable
domoticz@housespririt:~/domoticz/plugins/mijia-sensor-domoticz$
